export enum SectionType {
  HERO = 'HERO',
  TEXT_BLOCK = 'TEXT_BLOCK',
  IMAGE_BLOCK = 'IMAGE_BLOCK',
  FAQ = 'FAQ',
  CTA = 'CTA',
  TESTIMONIALS = 'TESTIMONIALS',
  FEATURES = 'FEATURES',
  GALLERY = 'GALLERY',
  BLOG_LIST = 'BLOG_LIST',
  CONTACT_FORM = 'CONTACT_FORM',
}
