import { Injectable, OnApplicationBootstrap } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import {
  CommunicationVariable,
  VariableCategoryGroup,
} from '@modules/communications/schemas/communication-variable.schema';

@Injectable()
export class CommunicationVariablesSeeder implements OnApplicationBootstrap {
  constructor(
    @InjectModel(CommunicationVariable.name)
    private readonly variableModel: Model<CommunicationVariable>,
  ) {}

  async onApplicationBootstrap() {
    // Delay run slightly to ensure DB connection is ready and other primary seeds complete
    setTimeout(async () => {
      try {
        await this.seed();
      } catch (err) {
        console.error('❌ Error seeding communication variables:', err);
      }
    }, 1500);
  }

  async seed() {
    const variables: Partial<CommunicationVariable>[] = [
      // ==========================================
      // 1. REGISTREE VARIABLES (REGISTRATION)
      // ==========================================
      {
        name: 'Registree ID',
        path: 'registreeId',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Unique ID of the registration record',
      },
      {
        name: 'Email Address',
        path: 'email',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        isSenderVariable: true,
        description: 'Primary email address of the attendee/registrant',
      },
      {
        name: 'Full Name',
        path: 'name',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Full name of the attendee/registrant',
      },
      {
        name: 'Event ID',
        path: 'eventId',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        ref: 'Event',
        description: 'Linked event reference ID',
      },
      {
        name: 'Website ID',
        path: 'websiteId',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        ref: 'Website',
        description: 'Linked website reference ID',
      },
      {
        name: 'Registered At Date',
        path: 'registeredAt',
        type: 'Date',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Timestamp when the attendee registered',
      },
      {
        name: 'Attendee ID',
        path: 'attendeeId',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Unique ID of the approved attendee',
      },
      {
        name: 'Ticket Pass Code',
        path: 'passCode',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Random ticket passcode or check-in verification code',
      },
      {
        name: 'Approved At Date',
        path: 'approvedAt',
        type: 'Date',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Timestamp when the registration was approved',
      },
      {
        name: 'Rejected At Date',
        path: 'rejectedAt',
        type: 'Date',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Timestamp when the registration was rejected',
      },
      {
        name: 'Blocked At Date',
        path: 'blockedAt',
        type: 'Date',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Timestamp when the attendee was blocked',
      },
      {
        name: 'Checked In At Date',
        path: 'checkedInAt',
        type: 'Date',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Timestamp when the attendee checked in at the event',
      },
      {
        name: 'Event Title',
        path: 'eventTitle',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Title of the associated event',
      },
      {
        name: 'Event Slug',
        path: 'eventSlug',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Slug of the associated event',
      },
      {
        name: 'Event Start Date',
        path: 'eventStartDate',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Start date of the event',
      },
      {
        name: 'Event Start Time',
        path: 'eventStartTime',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Start time of the event',
      },
      {
        name: 'Event Location',
        path: 'eventLocation',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Physical location or online meeting link summary',
      },
      {
        name: 'Website Name',
        path: 'websiteName',
        type: 'String',
        isArray: false,
        modelName: 'Registree',
        categoryGroup: VariableCategoryGroup.REGISTRATION,
        description: 'Name of the website through which registration occurred',
      },

      // ==========================================
      // 1.5 ATTENDEE VARIABLES (ATTENDEE)
      // ==========================================
      {
        name: 'Attendee ID',
        path: 'attendeeId',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        ref: 'Attendee',
        description: 'Unique attendee record ID',
      },
      {
        name: 'Attendee Name',
        path: 'name',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        description: 'Name of the attendee',
      },
      {
        name: 'Attendee Email',
        path: 'email',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        isSenderVariable: true,
        description: 'Email of the attendee',
      },
      {
        name: 'Event ID',
        path: 'eventId',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        ref: 'Event',
        description: 'ID of the event they are attending',
      },
      {
        name: 'Passcode',
        path: 'passCode',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        description: 'Unique passcode for the attendee',
      },
      {
        name: 'Registree ID',
        path: 'registreeId',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        ref: 'Registree',
        description: 'ID of the registree record linked to this attendee',
      },
      {
        name: 'Attendee Status',
        path: 'status',
        type: 'String',
        isArray: false,
        modelName: 'Attendee',
        categoryGroup: VariableCategoryGroup.ATTENDEE,
        description: 'Current status of the attendee',
      },

      // ==========================================
      // 2. NOMINATION VARIABLES (NOMINATION)
      // ==========================================
      {
        name: 'Nomination ID',
        path: 'nominationId',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Unique nomination record ID',
      },
      {
        name: 'Nominee Name',
        path: 'nomineeName',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Name of the nominated individual/team',
      },
      {
        name: 'Nominator Name',
        path: 'nominatorName',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Name of the nominator',
      },
      {
        name: 'Nominator Email',
        path: 'nominatorEmail',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        isSenderVariable: true,
        description: 'Email address of the nominator',
      },
      {
        name: 'Nominee Emails List',
        path: 'nomineeEmails',
        type: 'String',
        isArray: true,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        isSenderVariable: true,
        description: 'Array list of nominee email addresses',
      },
      {
        name: 'Nomination Session Title',
        path: 'sessionTitle',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Title of the nomination session/event',
      },
      {
        name: 'Submission Date',
        path: 'submittedAt',
        type: 'Date',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Timestamp when the nomination was submitted',
      },
      {
        name: 'Previous Status',
        path: 'previousStatus',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Previous state before update',
      },
      {
        name: 'New Status',
        path: 'newStatus',
        type: 'String',
        isArray: false,
        modelName: 'Nomination',
        categoryGroup: VariableCategoryGroup.NOMINATION,
        description: 'Current active state status of the nomination',
      },

      // ==========================================
      // 3. EVENT VARIABLES (EVENT)
      // ==========================================
      {
        name: 'Event ID',
        path: 'eventId',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Unique event identifier',
      },
      {
        name: 'Event Title',
        path: 'title',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Full title of the event',
      },
      {
        name: 'Event Slug',
        path: 'slug',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Slug of the event',
      },
      {
        name: 'Event Description',
        path: 'description',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Full description of the event',
      },
      {
        name: 'Event Excerpt',
        path: 'excerpt',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Short excerpt summary of the event',
      },
      {
        name: 'Event Type',
        path: 'type',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description:
          'Classification type of the event (e.g. webinar, physical)',
      },
      {
        name: 'Event Status',
        path: 'status',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Status of the event (e.g. DRAFT, PUBLISHED)',
      },
      {
        name: 'Event Start Date',
        path: 'startDate',
        type: 'Date',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Start date and time of the event',
      },
      {
        name: 'Event End Date',
        path: 'endDate',
        type: 'Date',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'End date and time of the event',
      },
      {
        name: 'Event Location Address',
        path: 'location.address',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Street address of the event venue',
      },
      {
        name: 'Event Location City',
        path: 'location.city',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'City of the event venue',
      },
      {
        name: 'Event Location Map Link',
        path: 'location.mapLink',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Google Maps or external map URL of the event venue',
      },
      {
        name: 'Event Location Latitude',
        path: 'location.lat',
        type: 'Number',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Latitude coordinate of the event venue',
      },
      {
        name: 'Event Location Longitude',
        path: 'location.lng',
        type: 'Number',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Longitude coordinate of the event venue',
      },
      {
        name: 'Event Meeting Link',
        path: 'meetingLink',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Virtual meeting or video stream link for the event',
      },
      {
        name: 'Meeting Room ID',
        path: 'meetingId',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Associated online meeting or room ID',
      },
      {
        name: 'Event Banner Image URL',
        path: 'bannerImage',
        type: 'String',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Banner image URL of the event',
      },
      {
        name: 'Websites list',
        path: 'websites',
        type: 'String',
        isArray: true,
        modelName: 'Event',
        ref: 'Website',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'List of website IDs linked to the event',
      },
      {
        name: 'Sponsors list',
        path: 'sponsors',
        type: 'String',
        isArray: true,
        modelName: 'Event',
        ref: 'Sponsor',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'List of sponsor IDs linked to the event',
      },
      {
        name: 'Event Invited Emails',
        path: 'invitedEmails',
        type: 'String',
        isArray: true,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        isSenderVariable: true,
        description: 'List of emails invited to the event',
      },
      {
        name: 'Event Total Registrations',
        path: 'totalRegistrations',
        type: 'Number',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Total number of registrants for the event',
      },
      {
        name: 'Event Is Active',
        path: 'isActive',
        type: 'Boolean',
        isArray: false,
        modelName: 'Event',
        categoryGroup: VariableCategoryGroup.EVENT,
        description: 'Whether the event is active',
      },

      // ==========================================
      // 4. BLOG VARIABLES (BLOG)
      // ==========================================
      {
        name: 'Blog ID',
        path: 'blogId',
        type: 'String',
        isArray: false,
        modelName: 'Blog',
        categoryGroup: VariableCategoryGroup.BLOG,
        description: 'Unique blog article ID',
      },
      {
        name: 'Blog Title',
        path: 'title',
        type: 'String',
        isArray: false,
        modelName: 'Blog',
        categoryGroup: VariableCategoryGroup.BLOG,
        description: 'Title of the blog post',
      },
      {
        name: 'Comment Author Name',
        path: 'authorName',
        type: 'String',
        isArray: false,
        modelName: 'Blog',
        categoryGroup: VariableCategoryGroup.BLOG,
        description: 'Name of the blog comment author',
      },
      {
        name: 'Comment Author Email',
        path: 'authorEmail',
        type: 'String',
        isArray: false,
        modelName: 'Blog',
        categoryGroup: VariableCategoryGroup.BLOG,
        isSenderVariable: true,
        description: 'Email address of the commenter',
      },

      // ==========================================
      // 5. CONTACT VARIABLES (CONTACT)
      // ==========================================
      {
        name: 'Contact Submitter Name',
        path: 'fullName',
        type: 'String',
        isArray: false,
        modelName: 'Contact',
        categoryGroup: VariableCategoryGroup.CONTACT,
        description: 'Full name of the contact form submitter',
      },
      {
        name: 'Contact Submitter Email',
        path: 'email',
        type: 'String',
        isArray: false,
        modelName: 'Contact',
        categoryGroup: VariableCategoryGroup.CONTACT,
        isSenderVariable: true,
        description: 'Email address of the contact form submitter',
      },
      {
        name: 'Requested Service',
        path: 'service',
        type: 'String',
        isArray: false,
        modelName: 'Contact',
        categoryGroup: VariableCategoryGroup.CONTACT,
        description: 'Specific service requested in the form',
      },
      {
        name: 'Contact Message Content',
        path: 'message',
        type: 'String',
        isArray: false,
        modelName: 'Contact',
        categoryGroup: VariableCategoryGroup.CONTACT,
        description: 'Full text message submitted by user',
      },

      // ==========================================
      // 6. WEBSITE VARIABLES (WEBSITE)
      // ==========================================
      {
        name: 'Website Name',
        path: 'name',
        type: 'String',
        isArray: false,
        modelName: 'Website',
        categoryGroup: VariableCategoryGroup.WEBSITE,
        description: 'Title of the CMS managed website',
      },
      {
        name: 'Website Domain',
        path: 'domain',
        type: 'String',
        isArray: false,
        modelName: 'Website',
        categoryGroup: VariableCategoryGroup.WEBSITE,
        description: 'Canonical domain name (e.g. example.com)',
      },

      // ==========================================
      // 7. SPONSOR VARIABLES (SPONSOR)
      // ==========================================
      {
        name: 'Sponsor Name',
        path: 'name',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Name of the sponsor/individual',
      },
      {
        name: 'Sponsor Company Name',
        path: 'companyName',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Company name of the sponsor',
      },
      {
        name: 'Sponsor Company Domain',
        path: 'companyDomain',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Domain name of the sponsor company',
      },
      {
        name: 'Sponsor Email',
        path: 'email',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        isSenderVariable: true,
        description: 'Email address of the sponsor',
      },
      {
        name: 'Sponsor Phone',
        path: 'phone',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Phone number of the sponsor',
      },
      {
        name: 'Sponsor Designation',
        path: 'designation',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Designation of the sponsor contact person',
      },
      {
        name: 'Sponsor Logo URL',
        path: 'logo',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Logo image URL of the sponsor',
      },
      {
        name: 'Sponsor Website URL',
        path: 'website',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Website URL of the sponsor',
      },
      {
        name: 'Sponsor Valuation',
        path: 'valuation',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Valuation tier details of the sponsor',
      },
      {
        name: 'Sponsor Type',
        path: 'type',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Sponsor type (e.g. Individual, Company)',
      },
      {
        name: 'Sponsor Tier',
        path: 'tier',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Sponsor tier (e.g. Platinum, Gold, Silver)',
      },
      {
        name: 'Sponsor Description',
        path: 'description',
        type: 'String',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Description summary of the sponsor',
      },
      {
        name: 'Sponsor Is Active',
        path: 'isActive',
        type: 'Boolean',
        isArray: false,
        modelName: 'Sponsor',
        categoryGroup: VariableCategoryGroup.SPONSOR,
        description: 'Whether the sponsor is active',
      },

      // ==========================================
      // 8. REPORT VARIABLES (REPORT)
      // ==========================================
      {
        name: 'Report ID',
        path: 'reportId',
        type: 'String',
        isArray: false,
        modelName: 'Report',
        categoryGroup: VariableCategoryGroup.REPORT,
        description: 'Unique report identifier',
      },
      {
        name: 'Report Title',
        path: 'reportTitle',
        type: 'String',
        isArray: false,
        modelName: 'Report',
        categoryGroup: VariableCategoryGroup.REPORT,
        description: 'Title of the report',
      },
      {
        name: 'Report Slug',
        path: 'reportSlug',
        type: 'String',
        isArray: false,
        modelName: 'Report',
        categoryGroup: VariableCategoryGroup.REPORT,
        description: 'Slug of the report',
      },
      {
        name: 'Report Description',
        path: 'reportDescription',
        type: 'String',
        isArray: false,
        modelName: 'Report',
        categoryGroup: VariableCategoryGroup.REPORT,
        description: 'Description of the report',
      },
      {
        name: 'Report Download URL',
        path: 'downloadUrl',
        type: 'String',
        isArray: false,
        modelName: 'Report',
        categoryGroup: VariableCategoryGroup.REPORT,
        description: 'Download link for the report',
      },
      {
        name: 'Report Download Count',
        path: 'reportDownloadCount',
        type: 'Number',
        isArray: false,
        modelName: 'Report',
        categoryGroup: VariableCategoryGroup.REPORT,
        description: 'Total number of times the report has been downloaded',
      },
    ];

    // Skip seeding if all variables already exist in the database
    const existingCount = await this.variableModel.countDocuments();
    if (existingCount >= variables.length) {
      console.log(
        `⏭️  Communication Variables already seeded (${existingCount} found). Skipping.`,
      );
      return;
    }

    let seededCount = 0;
    for (const variable of variables) {
      await this.variableModel.findOneAndUpdate(
        { modelName: variable.modelName, path: variable.path },
        { $set: variable },
        { upsert: true, returnDocument: 'after' },
      );
      seededCount++;
    }

    console.log(
      `✅ Seeded ${seededCount} Communication Variables successfully.`,
    );
  }
}
